// Mocks generated by Mockito 5.4.4 from annotations
// in rate_converter_flutter/test/unit_test/unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:isar/isar.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rate_converter_flutter/constant/country_code_constant.dart'
    as _i5;
import 'package:rate_converter_flutter/resources/favorite_countries_isar_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FavoriteCountryIsarRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteCountryIsarRepository extends _i1.Mock
    implements _i2.FavoriteCountryIsarRepository {
  MockFavoriteCountryIsarRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set isar(_i3.Isar? _isar) => super.noSuchMethod(
        Invocation.setter(
          #isar,
          _isar,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<List<String?>> getAllFavoriteCountries() => (super.noSuchMethod(
        Invocation.method(
          #getAllFavoriteCountries,
          [],
        ),
        returnValue: _i4.Future<List<String?>>.value(<String?>[]),
      ) as _i4.Future<List<String?>>);

  @override
  _i4.Future<void> add(_i5.CountryCode? code) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [code],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> delete(_i5.CountryCode? code) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [code],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> initializeIsarInstance(
          {required _i3.CollectionSchema<dynamic>? schema}) =>
      (super.noSuchMethod(
        Invocation.method(
          #initializeIsarInstance,
          [],
          {#schema: schema},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
